

const dictionary = [
  'ʻōweo',
  'kīloa',
  'māhao',
  'hāinu',
  'manoa',
  'mauli',
  'moʻou',
  'lūkia',
  'ʻaono',
  'kūlia',
  'olōlo',
  'hohiu',
  'ʻahea',
  'ōlaʻi',
  'ulana',
  'nōweo',
  'kepoa',
  'ʻowai',
  'nahoa',
  'ʻeiwa',
  'lokia',
  'lānui',
  'ninia',
  'hēleu',
  'mānai',
  'piʻoi',
  'ikamu',
  'mamua',
  'henua',
  'hīlea',
  'kuāua',
  'pūhau',
  'kiona',
  'kuapā',
  'haukī',
  'luaʻa',
  'kulua',
  'kukua',
  'unuhe',
  'mauki',
  'ʻakeu',
  'akakū',
  'ʻoaka',
  'ʻōpua',
  'kahau',
  'nākea',
  'ʻeleu',
  'pōhae',
  'hānau',
  'laulā',
  'hiʻia',
  'ʻinau',
  'kaima',
  'huika',
  'paʻao',
  'papau',
  'niole',
  'āhole',
  'mīkoi',
  'miula',
  'ʻakiu',
  'kiaka',
  'hihia',
  'heulu',
  'hikia',
  'huipū',
  'nāpai',
  'uhoʻi',
  'ʻaiʻē',
  'mākoe',
  'ʻāweu',
  'kelea',
  'kaihe',
  'neʻeu',
  'hanua',
  'koniā',
  'anana',
  'ānewa',
  'pūkai',
  'ʻoāwa',
  'ʻaeʻa',
  'mānae',
  'poahi',
  'owāwa',
  'lukua',
  'penei',
  'ālulu',
  'lauwī',
  'woela',
  'akāka',
  'ʻoali',
  'kiʻai',
  'maila',
  'hūʻeu',
  'ʻīnio',
  'pāhoe',
  'lāuli',
  'mākiu',
  'piohē',
  'kāehu',
  'nanau',
  'moloā',
  'laikī',
  'unahe',
  'ʻanae',
  'nanai',
  'hainā',
  'leokū',
  'lāhoe',
  'maoki',
  'ʻakiu',
  'ʻīhoe',
  'māwao',
  'ihukū',
  'māʻeo',
  'ʻalua',
  'kuawa',
  'ʻelua',
  'kului',
  'noela',
  'nohae',
  'hāunu',
  'pīʻao',
  'pāloa',
  'kaiao',
  'ōpuhe',
  'noelo',
  'kowaū',
  'kawea',
  'waiho',
  'kaala',
  'kūoʻe',
  'uheʻe',
  'polie',
  'waihā',
  'pākau',
  'ʻeiʻa',
  'iahai',
  'kōlea',
  'manie',
  'anahā',
  'puaʻi',
  'kāpua',
  'pukua',
  'meneū',
  'wiliō',
  'waikī',
  'kauna',
  'heheo',
  'kokoa',
  'ulūlu',
  'ʻaoka',
  'kawoa',
  'kuʻua',
  'pāuma',
  'kōloa',
  'pehua',
  'puʻoa',
  'noneā',
  'nenei',
  'ʻuala',
  'pāʻao',
  'uauai',
  'māihi',
  'mahae',
  'kūloa',
  'ukana',
  'wēkiu',
  'uhuao',
  'unūnu',
  'ʻoeke',
  'luahi',
  'hākui',
  'iheʻō',
  'hinua',
  'ʻōuli',
  'ʻaeko',
  'kāʻeo',
  'olowī',
  'kiʻei',
  'waikū',
  'noʻao',
  'onena',
  'pōniu',
  'moaka',
  'auele',
  'ʻahao',
  'leleu',
  'paūhu',
  'mimio',
  'kūhau',
  'lēhai',
  'menui',
  'lānia',
  'nahae',
  'ʻulea',
  'mōwae',
  'peleu',
  'kūana',
  'auoha',
  'laʻia',
  'kālua',
  'ʻiewe',
  'ʻunua',
  'ʻonou',
  'kokoe',
  'kuʻia',
  'ʻalae',
  'māʻau',
  'luana',
  'ʻoala',
  'hānui',
  'keoma',
  'kēwai',
  'ʻūlou',
  'hopai',
  'ulukū',
  'mauka',
  'mōhio',
  'pāoni',
  'pāleo',
  'kuana',
  'ʻāina',
  'kāoʻo',
  'loloa',
  'noili',
  'ʻeono',
  'elelo',
  'kōelo',
  'kālai',
  'puolo',
  'ʻākia',
  'ʻelua',
  'nahua',
  'kūʻau',
  'mukau',
  'hākiu',
  'uhole',
  'īheʻe',
  'hoene',
  'hīlia',
  'poʻou',
  'kuʻia',
  'kākai',
  'pīʻoe',
  'epani',
  'kauhi',
  'ʻīkoi',
  'nonoi',
  'nāihe',
  'helea',
  'nākai',
  'ʻaukā',
  'kīlou',
  'maika',
  'pōhai',
  'hākei',
  'mōlia',
  'ʻōmea',
  'kiloi',
  'unoho',
  'ʻehia',
  'kāmae',
  'kēʻae',
  'pānoa',
  'lākiō',
  'koihā',
  'ʻauʻa',
  'mākoi',
  'ekele',
  'paiho',
  'hoelo',
  'nauwe',
  'nanae',
  'konia',
  'koili',
  'uwaki',
  'moaʻe',
  'koaʻe',
  'puaʻō',
  'ʻaiʻē',
  'ʻopae',
  'nomea',
  'kopea',
  'lāhei',
  'ʻaukā',
  'huehu',
  'pōhue',
  'ʻōiwi',
  'ʻaolo',
  'ʻōali',
  'ʻueke',
  'nūnea',
  'uwapo',
  'hāmoa',
  'ualei',
  'nilea',
  'hāwai',
  'meheu',
  'uwahi',
  'hōpoe',
  'huāle',
  'ʻimia',
  'hakua',
  'hekau',
  'māhea',
  'pupue',
  'kūkai',
  'hīnau',
  'huipa',
  'unukā',
  'huene',
  'ʻāhua',
  'olonā',
  'mākou',
  'kuemi',
  'ulehe',
  'lānai',
  'ʻiako',
  'nākao',
  'ʻōpao',
  'maahe',
  'ʻāhiu',
  'hanoa',
  'kāhoa',
  'ulahi',
  'pāpai',
  'nanao',
  'kaika',
  'nūkea',
  'keanu',
  'aliʻi',
  'maheu',
  'ʻelia',
  'malai',
  'hēpia',
  'unala',
  'hauka',
  'pūnao',
  'līloa',
  'puakō',
  'pauoa',
  'mākau',
  'hulei',
  'alana',
  'paʻea',
  'ʻōnou',
  'huapī',
  'kaʻio',
  'pania',
  'kiaʻi',
  'hāpai',
  'limua',
  'heana',
  'elehu',
  'poaʻe',
  'pākeu',
  'ʻōwae',
  'kāleo',
  'akaka',
  'pipio',
  'hāliu',
  'lehia',
  'moʻau',
  'ʻākau',
  'kuali',
  'momio',
  'mānoa',
  'puaʻa',
  'ʻauia',
  'ʻuwao',
  'haoʻe',
  'kīheu',
  'kōāwā',
  'uhele',
  'wekea',
  'maiko',
  'ʻohia',
  'māewa',
  'kīhoe',
  'hāiki',
  'lukau',
  'poʻea',
  'ʻeleī',
  'pōuhu',
  'kūakā',
  'uhalu',
  'līwai',
  'uholo',
  'ʻāinu',
  'mālia',
  'uahoa',
  'māino',
  'uhemo',
  'poila',
  'lauia',
  'koʻoū',
  'lakio',
  'pauma',
  'ʻāhia',
  'aniau',
  'kawai',
  'hōpue',
  'ʻōpio',
  'kuhue',
  'kuila',
  'ʻuleu',
  'pūkea',
  'ʻōpae',
  'kāmoe',
  'pōlio',
  'pōʻai',
  'unana',
  'kaila',
  'kūʻai',
  'iliau',
  'paula',
  'ʻōkai',
  'ʻulua',
  'hāoʻo',
  'napoe',
  'noulu',
  'mamao',
  'unuhi',
  'leina',
  'kuaʻi',
  'ʻauka',
  'maoha',
  'mākia',
  'laila',
  'ālālā',
  'pokoa',
  'koine',
  'naiʻa',
  'kaʻao',
  'molea',
  'kuhia',
  'kalia',
  'māiki',
  'hakia',
  'koukā',
  'ʻeʻoe',
  'ʻonia',
  'paena',
  'mahua',
  'pauhū',
  'pelua',
  'puoho',
  'hōkio',
  'holoi',
  'lūʻau',
  'pakai',
  'ʻūkiu',
  'ʻōlae',
  'aʻapu',
  'oʻoʻo',
  'kākea',
  'kipao',
  'hāʻae',
  'pīhoi',
  'ʻeʻea',
  'nīhoa',
  'maliu',
  'enene',
  'pūlua',
  'koloa',
  'kiaʻi',
  'lehea',
  'kaulī',
  'meʻeu',
  'ʻoulu',
  'nāuki',
  'uakea',
  'ihihī',
  'pūalu',
  'kueʻo',
  'mākua',
  'ʻānai',
  'haupa',
  'huakō',
  'līhau',
  'aeāea',
  'kīpou',
  'hulia',
  'ʻōmau',
  'paihō',
  'māono',
  'kaulu',
  'ʻōhea',
  'aʻaʻa',
  'piʻia',
  'hōuna',
  'olaʻi',
  'poukū',
  'ulaia',
  'alaia',
  'pūʻuo',
  'ʻokia',
  'keahi',
  'pūʻau',
  'makua',
  'nīele',
  'pōlea',
  'huhui',
  'hōʻea',
  'kuwai',
  'kāoko',
  'nauki',
  'kupae',
  'naʻau',
  'lonoa',
  'ʻekua',
  'ʻōhua',
  'kaula',
  'uluhe',
  'piano',
  'luapō',
  'kahua',
  'hopua',
  'kīnai',
  'ʻauae',
  'laʻoa',
  'puoʻa',
  'momoa',
  'ʻakoa',
  'kāhea',
  'hikua',
  'kapae',
  'piaea',
  'pouli',
  'pauka',
  'punia',
  'uouoa',
  'ʻīlio',
  'hiona',
  'poina',
  'pāuhi',
  'ʻōhua',
  'ʻauʻa',
  'alena',
  'leleū',
  'kāuna',
  'ananū',
  'kekal',
  'haika',
  'wauke',
  'lolio',
  'koele',
  'maluā',
  'pūʻao',
  'puʻua',
  'ʻīnia',
  'ulima',
  'nokea',
  'ʻaila',
  'koaka',
  'pelio',
  'paina',
  'oʻahu',
  'ulele',
  'ahuoi',
  'mōpua',
  'malae',
  'koaha',
  'kāʻei',
  'nanea',
  'ʻēheu',
  'laukī',
  'hāpue',
  'koaea',
  'wāiʻa',
  'paika',
  'lēhau',
  'hāweo',
  'mulei',
  'heehe',
  'hālau',
  'naele',
  'wālua',
  'līmoa',
  'pekua',
  'kōpia',
  'lohia',
  'pinao',
  'āmuka',
  'hkkal',
  'hāpou',
  'ʻuiwi',
  'uhoni',
  'ānehe',
  'hauli',
  'huila',
  'nīnau',
  'ʻahia',
  'luhea',
  'mākai',
  'pāheu',
  'māiʻo',
  'ʻāloa',
  'wikiō',
  'ākēkē',
  'ʻōiki',
  'akuʻe',
  'kākou',
  'ēlama',
  'kāhiu',
  'heona',
  'mūhea',
  'pāpio',
  'makao',
  'pāuli',
  'ʻiamo',
  'paukū',
  'ʻoene',
  'oloea',
  'puhia',
  'leiʻō',
  'ōpuna',
  'wēlau',
  'ʻomua',
  'nepue',
  'lanau',
  'lehua',
  'kūnae',
  'ʻekue',
  'puana',
  'kāula',
  'ʻoiai',
  'kūlua',
  'naika',
  'kōʻie',
  'pīʻai',
  'hāuli',
  'ōlaʻa',
  'kiuna',
  'okōko',
  'melia',
  'pōaka',
  'kanea',
  'kōmou',
  'lūʻau',
  'ʻaika',
  'hōʻau',
  'meine',
  'ʻiole',
  'hakai',
  'nīheu',
  'lāmia',
  'lauʻō',
  'kawia',
  'hahai',
  'auahi',
  'humea',
  'kuina',
  'ulupē',
  'ʻaina',
  'kuehu',
  'ululā',
  'haukō',
  'walea',
  'loina',
  'uwaʻu',
  'kiawe',
  'pāmia',
  'omōhā',
  'ahāhā',
  'ʻāuli',
  'ʻīnia',
  'huaʻi',
  'iwikū',
  'kāwae',
  'piolo',
  'mauae',
  'iulai',
  'kokoi',
  'poʻiu',
  'ʻōheu',
  'kīhei',
  'aulau',
  'hokua',
  'kaina',
  'lāʻie',
  'iākua',
  'māhua',
  'ʻūomo',
  'kiapā',
  'piena',
  'ālaka',
  'kūpea',
  'pualu',
  'nakue',
  'nāele',
  'mīʻoi',
  'ʻōmou',
  'huaka',
  'ʻeʻeu',
  'ʻōiwi',
  'waina',
  'mōuki',
  'ʻākau',
  'kuaio',
  'ʻāhiu',
  'pākūā',
  'nahau',
  'pīʻoe',
  'hāpua',
  'moena',
  'maiao',
  'lōhiu',
  'makou',
  'puoni',
  'kīkoi',
  'kekea',
  'nāweo',
  'mākea',
  'nāwao',
  'pōliu',
  'ʻoawa',
  'iʻole',
  'meʻea',
  'kunia',
  'kkkal',
  'ʻōahi',
  'nenea',
  'unahi',
  'lōhai',
  'ʻawea',
  'makea',
  'kēpau',
  'puihe',
  'kāʻēē',
  'liona',
  'niape',
  'honia',
  'leleo',
  'nōiki',
  'ʻīlio',
  'ukoʻa',
  'lēkiō',
  'mōkoi',
  'pokea',
  'uwali',
  'keawe',
  'poehi',
  'uwepa',
  'ʻalea',
  'ʻilau',
  'haili',
  'huakē',
  'ilina',
  'noiʻo',
  'ʻunae',
  'kaupē',
  'ōhāhā',
  'unele',
  'lepea',
  'ihona',
  'kūkoa',
  'moana',
  'mahea',
  'ʻauka',
  'ʻōhio',
  'kuapo',
  'mania',
  'lāhea',
  'kaomi',
  'ʻaʻea',
  'lamie',
  'ʻōaʻa',
  'wāwae',
  'pōheo',
  'kunou',
  'nanue',
  'kāʻei',
  'kōhia',
  'hōlei',
  'ʻūʻua',
  'kione',
  'hāloa',
  'pāoʻo',
  'kāpae',
  'meiwi',
  'pūwai',
  'nīane',
  'kāohi',
  'panau',
  'ukali',
  'haele',
  'pahua',
  'lumia',
  'puewa',
  'lekue',
  'kaīkū',
  'hinao',
  'aʻukī',
  'nipoa',
  'pūʻai',
  'kāʻai',
  'kalea',
  'kāmau',
  'kiʻoa',
  'kānoa',
  'hupau',
  'ʻāiki',
  'lawea',
  'huali',
  'kūmoe',
  'ʻaihē',
  'hahau',
  'ʻūlau',
  'hoaka',
  'hāuna',
  'pōkue',
  'ʻēheu',
  'ʻānae',
  'ʻeʻei',
  'lākea',
  'hehia',
  'nunui',
  'launa',
  'māmio',
  'ʻāwai',
  'kuoni',
  'ʻoupē',
  'mānui',
  'huaʻā',
  'maine',
  'holea',
  'kaena',
  'pīwai',
  'kēhue',
  'ʻoiʻo',
  'ʻainā',
  'kāwao',
  'hahae',
  'oʻole',
  'kīʻei',
  'kapao',
  'kāili',
  'haole',
  'anaka',
  'ʻōana',
  'kaupō',
  'wāhia',
  'ʻouwo',
  'ʻewai',
  'lāhai',
  'hiana',
  'hohoa',
  'ʻaʻao',
  'ʻanau',
  'luehu',
  'kūnou',
  'pāwai',
  'uwalo',
  'aoaoa',
  'moekū',
  'niolo',
  'pouna',
  'helua',
  'maiʻa',
  'kumia',
  'huana',
  'lamia',
  'pēheu',
  'poeko',
  'nīʻau',
  'pāʻia',
  'ikehu',
  'kōahe',
  'puiki',
  'koani',
  'holoē',
  'līpoa',
  'kauka',
  'peawa',
  'uhaku',
  'ʻaiwa',
  'nauwā',
  'kinai',
  'olowā',
  'haena',
  'kēlia',
  'haona',
  'hāʻea',
  'lālea',
  'kapuō',
  'ʻokia',
  'kēlou',
  'leioa',
  'hāʻoi',
  'paiʻā',
  'mouku',
  'uhakē',
  'ʻēkeu',
  'ʻōnea',
  'uwila',
  'memea',
  'kūhou',
  'huelo',
  'kaini',
  'hōʻae',
  'paona',
  'naʻau',
  'ʻaoʻo',
  'akena',
  'kauwō',
  'haoma',
  'wehea',
  'hiliu',
  'ʻiele',
  'pepeu',
  'auolo',
  'kāhua',
  'pōuli',
  'pīkoi',
  'kaola',
  'mōkio',
  'honoā',
  'nānue',
  'pēkeu',
  'ʻāpeu',
  'uhaki',
  'monia',
  'uhinu',
  'ʻīnea',
  'unaue',
  'pāpua',
  'ikīki',
  'kāina',
  'waipā',
  'koeʻā',
  'koiʻi',
  'ʻāina',
  'kākau',
  'kāʻao',
  'uweka',
  'mīʻoi',
  'koina',
  'hihiu',
  'uwene',
  'huaʻi',
  'kīlua',
  'ʻuniu',
  'nōkea',
  'ʻuwia',
  'lāhui',
  'ʻaʻau',
  'wākea',
  'popoe',
  'kīlau',
  'ukoʻo',
  'kūhoe',
  'hōʻoi',
  'keola',
  'palea',
  'līkao',
  'māhuā',
  'ʻowau',
  'huhue',
  'hoʻia',
  'lōuhu',
  'huʻea',
  'wauau',
  'nonoā',
  'ʻoʻoi',
  'pōlua',
  'kuhua',
  'pūheu',
  'ʻaʻei',
  'lipoa',
  'kūʻai',
  'puali',
  'nonea',
  'pākea',
  'luhia',
  'koene',
  'ʻoulu',
  'ʻōʻio',
  'ihola',
  'kuolo',
  'līlia',
  'lelea',
  'nuʻao',
  'ahana',
  'poʻia',
  'anena',
  'pūniu',
  'moala',
  'kīhae',
  'naluā',
  'keʻei',
  'manuā',
  'kīleo',
  'kāheu',
  'ʻiole',
  'kameo',
  'aumoe',
  'ʻāone',
  'olopī',
  'ʻaʻae',
  'kiʻia',
  'pehia',
  'leikō',
  'ʻōpua',
  'okoko',
  'līoho',
  'pilia',
  'kīloi',
  'keʻia',
  'upupā',
  'kawaū',
  'kaiwi',
  'huina',
  'ʻaiau',
  'wāwau',
  'lokou',
  'paila',
  'kuini',
  'māunu',
  'hahao',
  'haʻua',
  'ukamu',
  'pūnua',
  'alakō',
  'ʻāhai',
  'puapu',
  'halei',
  'laula',
  'laiki',
  'kuahu',
  'kuamū',
  'nenue',
  'kōʻai',
  'ʻuiki',
  'kaniu',
  'keiki',
  'nānai',
  'kuiki',
  'kahuā',
  'puehu',
  'keaka',
  'omoki',
  'puawa',
  'hīkau',
  'lōkea',
  'kepue',
  'kaʻeo',
  'omomo',
  'haiau',
  'piaia',
  'heaha',
  'manae',
  'hoiʻa',
  'aʻelā',
  'ʻoliō',
  'māhie',
  'kūlou',
  'hukia',
  'ʻāahi',
  'ʻaʻai',
  'lolia',
  'kiloū',
  'ʻikea',
  'lupea',
  'lūpua',
  'mauwā',
  'koelo',
  'pihoa',
  'weweo',
  'mūkei',
  'piele',
  'haoʻa',
  'hoʻoā',
  'hūwai',
  'kiana',
  'haiwā',
  'ʻūlei',
  'kolia',
  'ālolo',
  'moani',
  'hōwai',
  'kūono',
  'wiola',
  'ukupē',
  'pālau',
  'pēkoi',
  'alelo',
  'hāʻae',
  'ʻēlau',
  'hiena',
  'kuewa',
  'pakoa',
  'lāʻau',
  'mauʻu',
  'oloʻū',
  'kalae',
  'poluā',
  'hāʻei',
  'leʻie',
  'paiwa',
  'lekiō',
  'kākua',
  'kuaka',
  'auēuē',
  'wawai',
  'lomia',
  'hōlua',
  'kalio',
  'hāmau',
  'honua',
  'pinau',
  'kīlea',
  'kielo',
  'ʻaiea',
  'panua',
  'ʻapai',
  'hehei',
  'kuiwa',
  'hākia',
  'koana',
  'nohea',
  'akule',
  'mōʻiu',
  'pāiki',
  'kaona',
  'kuaʻā',
  'palai',
  'hului',
  'lahui',
  'hōʻai',
  'lēʻia',
  'niuhi',
  'minoi',
  'kahiō',
  'ʻiomo',
  'ʻoloa',
  'pūhai',
  'mamae',
  'maunu',
  'ʻaʻoe',
  'kōheo',
  'ʻikuā',
  'uleʻo',
  'hāleu',
  'wilia',
  'ehehe',
  'kūʻou',
  'ōlaʻi',
  'nehoa',
  'loaʻa',
  'hākai',
  'momoe',
  'lēkei',
  'maina',
  'paukī',
  'lukia',
  'mīhau',
  'ʻānoa',
  'hoʻāo',
  'kuene',
  'ʻapoa',
  'hōʻoā',
  'kaʻau',
  'kueka',
  'kāmoa',
  'lūkea',
  'hiapo',
  'mokae',
  'nīʻau',
  'lakua',
  'hiolo',
  'palau',
  'ʻōhao',
  'hāʻao',
  'mamau',
  'maoli',
  'kūola',
  'kaolo',
  'kakau',
  'hoana',
  'nalea',
  'olokē',
  'mālei',
  'pupua',
  'ʻānai',
  'laina',
  'lalau',
  'koali',
  'kēpia',
  'poepe',
  'ʻaloe',
  'ʻehia',
  'kūoʻo',
  'ʻulae',
  'ʻiawe',
  'kukui',
  'miona',
  'kuala',
  'pūhui',
  'ʻēlau',
  'mumui',
  'nāulu',
  'puahi',
  'noʻoa',
  'ahulu',
  'māwai',
  'kōkio',
  'alani',
  'ulupō',
  'lolea',
  'noiʻi',
  'houpo',
  'aulia',
  'makai',
  'hūkeu',
  'pāono',
  'ponia',
  'ʻāmui',
  'pīkai',
  'lonoā',
  'lālau',
  'oʻoʻō',
  'kūmau',
  'makāu',
  'upiʻi',
  'pehea',
  'kaupā',
  'kuaʻi',
  'hānei',
  'kuoho',
  'lilio',
  'keoho',
  'kōʻiu',
  'puoko',
  'pāhau',
  'heiau',
  'nihoa',
  'mekia',
  'loala',
  'kūhiō',
  'naʻuā',
  'linoa',
  'milia',
  'kamoe',
  'mōlio',
  'kaikā',
  'eʻehu',
  'aumoa',
  'mauna',
  'mahai',
  'mōnea',
  'pepei',
  'ānini',
  'wahie',
  'luaʻi',
  'uhaʻi',
  'makoa',
  'ununa',
  'pokia',
  'kueni',
  'ʻoehu',
  'puakī',
  'unoʻo',
  'kīkau',
  'laukō',
  'māilo',
  'hālua',
  'panoa',
  'mōhai',
  'kōnui',
  'keʻeo',
  'kūnoa',
  'kiola',
  'puawe',
  'pōʻai',
  'ʻuaʻu',
  'ʻānia',
  'kōkia',
  'līʻoa',
  'manua',
  'hūkai',
  'hiaʻā',
  'ukole',
  'polai',
  'mālua',
  'holua',
  'loulu',
  'māina',
  'klkal',
  'maiau',
  'kēuli',
  'kuaʻe',
  'ahukū',
  'leuwī',
  'pāhai',
  'anilā',
  'hōkai',
  'mulea',
  'ahuna',
  'kēhau',
  'waipū',
  'kaela',
  'awāwa',
  'kaʻao',
  'kūkae',
  'pīʻei',
  'ʻunia',
  'maile',
  'kāhei',
  'ʻākea',
  'olopē',
  'heaʻe',
  'kohea',
  'kūawa',
  'pukai',
  'ʻaina',
  'kōkua',
  'kīhau',
  'ʻāhia',
  'lekia',
  'pāhia',
  'nopue',
  'hākau',
  'kīpau',
  'lauʻī',
  'lohea',
  'hihio',
  'pioea',
  'hahei',
  'hōʻio',
  'paipu',
  'akula',
  'nāmua',
  'pānie',
  'alawī',
  'ʻōhai',
  'kualo',
  'kuālo',
  'pānai',
  'lāʻau',
  'lālei',
  'pēkau',
  'piuka',
  'mīana',
  'māhoe',
  'aouli',
  'ʻūniu',
  'ʻāuna',
  'puela',
  'āloʻi',
  'minao',
  'kaohi',
  'aʻela',
  'hauhō',
  'lanai',
  'pilau',
  'ʻēkea',
  'ʻaioā',
  'mikaō',
  'kēlau',
  'uluna',
  'ʻauae',
  'maluō',
  'ʻuehe',
  'kūpau',
  'pālua',
  'mānea',
  'māuna',
  'kohai',
  'uianu',
  'auhea',
  'māʻoi',
  'hauna',
  'kaiko',
  'paoka',
  'lēhei',
  'hoʻea',
  'kāhai',
  'huini',
  'hākea',
  'ūkākā',
  'māhoa',
  'naule',
  'pīʻai',
  'māwae',
  'hoena',
  'pihea',
  'pouka',
  'haaʻa',
  'kaiua',
  'ukuhi',
  'aloha',
  'paʻau',
  'hōʻae',
  'kūkia',
  'kupai',
  'ʻōilo',
  'neʻia',
  'uweko',
  'kioea',
  'pāwao',
  'kuahā',
  'leiau',
  'kuelo',
  'hōkeo',
  'uwoki',
  'kākia',
  'laimi',
  'luina',
  'ʻaiwi',
  'pāumu',
  'puaea',
  'kioia',
  'uhuki',
  'nunoi',
  'ʻiolo',
  'ʻaʻai',
  'malia',
  'paihī',
  'pōule',
  'wīlou',
  'oloʻa',
  'kōina',
  'hōʻeu',
  'paʻia',
  'kalua',
  'māuli',
  'uhipū',
  'ʻāpua',
  'niniu',
  'kaiue',
  'pāhoa',
  'ʻumia',
  'mālie',
  'poliō',
  'nōhie',
  'kiʻei',
  'kualā',
  'halia',
  'keopu',
  'kuoha',
  'ʻōpio',
  'kiele',
  'kakae',
  'kāloa',
  'helei',
  'piuke',
  'liʻua',
  'oneʻā',
  'pāola',
  'ahona',
  'kōnea',
  'uluʻā',
  'piula',
  'ehaha',
  'anaʻē',
  'kupua',
  'āneho',
  'waena',
  'poale',
  'ihuʻū',
  'kauwā',
  'kūliu',
  'hāehu',
  'kiule',
  'malau',
  'ʻōniu',
  'kiani',
  'panea',
  'papao',
  'kahia',
  'kāwai',
  'pahiō',
  'alehu',
  'wawau',
  'kāmua',
  'kikoa',
  'kālau',
  'hānai',
  'ʻāoʻo',
  'hōlio',
  'makau',
  'ʻiona',
  'paiki',
  'kuili',
  'mikia',
  'uhina',
  'unoʻa',
  'ūpēpē',
  'ʻōlea',
  'moano',
  'ulihi',
  'kūhea',
  'kaunu',
  'ʻuala',
  'pāweo',
  'hoʻāu',
  'koena',
  'waele',
  'pāuhu',
  'kainō',
  'ʻolua',
  'uaiki',
  'pāiwa',
  'lākou',
  'nāiʻi',
  'kiupe',
  'mēkia',
  'holoa',
  'mauʻu',
  'kemua',
  'paioa',
  'nioke',
  'nihia',
  'kūpou',
  'haina',
  'ʻākea',
  'ʻāhui',
  'luʻua',
  'ʻōhui',
  'kenia',
  'noiʻi',
]

const targetWords = ['aliʻi', 'akula', 'lākou', 'ʻāina', 'ihola', 'maila', 'ʻoiai', 'aʻela', 'hōʻea', 'laila', 'kākou', 'haole', 'maoli', 'waena', 'loaʻa', 'aloha', 'oʻahu', 'ʻōpio', 'keiki', 'ʻelua', 'makua', 'waiho', 'heiau', 'kākau', 'kahua', 'lāʻau', 'moana', 'kōkua', 'nīnau', 'hānai', 'mākou', 'kāhea', 'keʻei', 'hānau', 'lāhui', 'ukali', 'puaʻa', 'wāwae', 'kiaʻi', 'hahai', 'mākua', 'nunui', 'ʻīkoi', 'ʻākau', 'māhoe', 'niuhi', 'makoa', 'kaula', 'mōhai', 'hāpai', 'penei', 'ʻāhia', 'lālau', 'ʻeleu', 'mālie', 'keawe', 'ʻolua', 'honua', 'kālua', 'mauna', 'māwae', 'pehea', 'lehua', 'kūʻai', 'uhaʻi', 'mauʻu', 'lehia', 'kāula', 'awāwa', 'ʻeono', 'kālai', 'hauna', 'paukū', 'poina', 'ʻauʻa', 'moena', 'mamao', 'ʻuala', 'maliu', 'kaihe', 'hekau', 'meheu', 'launa', 'ʻōuli', 'kaupō', 'kūlou', 'waele', 'kukui', 'ʻoulu', 'ukana', 'pauka', 'naʻau', 'ʻōniu', 'loloa', 'ʻīlio', 'hōʻeu', 'nanea', 'nonoi', 'noiʻi', 'maika', 'koena', 'pālau', 'laulā', 'kaʻao', 'hālau', 'uhaki', 'wauke', 'okōko', 'kāuna', 'maiʻa', 'hahau', 'ʻāhiu', 'kiola', 'ʻōiwi', 'uhuki', 'kiʻei', 'anana', 'ʻehia', 'huina', 'kaena', 'pūniu', 'kuapā', 'ʻeiwa', 'pāhoa', 'hōʻoi', 'ʻaina', 'kīhei', 'hāmau', 'mākia', 'heana', 'unuhi', 'kūhiō', 'niniu', 'nāihe', 'kainō', 'kuemi', 'ʻāhua', 'līloa', 'hākau', 'ʻanae', 'pouli', 'kinai', 'loina', 'olonā', 'huila', 'kaiao', 'akāka', 'mōlia', 'maile', 'kāmoe', 'hoʻāo', 'kunou', 'pōniu', 'wahie', 'luaʻi', 'kēhau', 'ʻūlei', 'ʻiako', 'hiolo', 'hihia', 'akena', 'hāʻao', 'hāiki', 'kūlia', 'ʻonou', 'hāuna', 'makau', 'ʻōpua', 'ʻikuā', 'ʻōnou', 'puaʻi', 'houpo', 'luahi', 'ʻoaka', 'luina', 'naele', 'kūlua', 'nākai', 'iulai', 'aumoe', 'manuā', 'maunu', 'haupa', 'lānai', 'puehu', 'pōʻai', 'ʻāoʻo', 'haele', 'nanao', 'pōhue', 'hoana', 'kāohi', 'holoi', 'pālua', 'heulu', 'kāʻeo', 'hokua', 'kāpae', 'ʻaeʻa', 'kaona', 'kuʻia', 'ʻalae', 'laukī', 'kākia', 'ʻēheu', 'kāmau', 'ōlaʻi', 'hōʻoā', 'kaʻau', 'uwaʻu', 'pauoa', 'kuili', 'paʻao', 'nīʻau', 'uianu', 'pīkai', 'ulele', 'kuene', 'paila', 'kāoʻo', 'uhalu', 'hāloa', 'kīlou', 'ʻiewe', 'kupua', 'kuehu', 'kalae', 'līwai', 'haili', 'puana', 'ulana', 'haoʻa', 'ʻāhui', 'hahae', 'keanu', 'kuala', 'lupea', 'maiau', 'ʻōmea', 'kaʻeo', 'ikīki', 'ʻaila', 'kēwai', 'keoho', 'mālia', 'ʻāpua', 'puakō', 'hāmoa', 'lēhau', 'neʻeu', 'kuana', 'mulea', 'ʻoāwa', 'ʻumia', 'kawai', 'ʻōhua', 'ʻōmau', 'pahua', 'huhui', 'paina', 'mahae', 'huelo', 'lāʻie', 'kēpau', 'kūoʻo', 'kuewa', 'nahae', 'ʻīnea', 'pōlua', 'kualā', 'pīkoi', 'keaka', 'pāʻia', 'kaohi', 'lāuli', 'pouli', 'hauli', 'kāʻei', 'mania', 'hiena', 'wēkiu', 'pinau', 'kānoa', 'ʻūkiu', 'helei', 'puoko', 'ʻueke', 'māino', 'laula', 'hului', 'mīʻoi', 'kākua', 'hōʻea', 'pelio', 'piele', 'anaka', 'iwikū', 'kalua', 'ʻiole', 'hinua', 'nāulu', 'hihiu', 'ʻikea', 'hōkeo', 'mauli', 'mouku', 'hoaka', 'auoha', 'kuāua', 'kīloi', 'ʻauae', 'wēlau', 'ānehe', 'hainā', 'kuini', 'ukupē', 'akule', 'liona', 'keʻeo', 'lūʻau', 'nāuki', 'hoʻia', 'kīhae', 'puʻua', 'kahuā', 'kūliu', 'puela', 'aʻelā', 'ʻalua', 'ulukū', 'pāʻao', 'uwahi', 'leina', 'ʻānae', 'ʻaʻau', 'pāuli', 'kaulu', 'nomea', 'mōlio', 'lalau', 'malau', 'ʻōahi', 'wākea', 'kekea', 'nanai', 'līhau', 'ihona', 'ʻaʻai', 'mānoa', 'waikī', 'haika', 'koaʻe', 'pāpio', 'līpoa', 'pinao', 'ʻoʻoi', 'ʻāweu', 'waipā', 'hiapo', 'kaniu', 'kiapā', 'ʻaukā', 'hāweo', 'ʻōhai', 'puoho', 'loulu', 'kīnai']

const WORD_LENGTH = 5
const FLIP_ANIMATION_DURATION = 500
const DANCE_ANIMATION_DURATION = 500
const keyboard = document.querySelector("[data-keyboard]")
const alertContainer = document.querySelector("[data-alert-container]")
const guessGrid = document.querySelector("[data-guess-grid]")
const offsetFromDate = new Date(2023, 6, 9)
const msOffset = Date.now() - offsetFromDate
const dayOffset = msOffset / 1000 / 60 / 60 / 24
const targetWord = targetWords[Math.floor(dayOffset) % targetWords.length]

startInteraction()
  
  function startInteraction() {
    document.addEventListener("click", handleMouseClick)
    document.addEventListener("keydown", handleKeyPress)
  }
  
  function stopInteraction() {
    document.removeEventListener("click", handleMouseClick)
    document.removeEventListener("keydown", handleKeyPress)
  }
  
  function handleMouseClick(e) {
    if (e.target.matches("[data-key]")) {
      pressKey(e.target.dataset.key)
      return
    }
  
    if (e.target.matches("[data-enter]")) {
      submitGuess()
      return
    }
  
    if (e.target.matches("[data-delete]")) {
      deleteKey()
      return
    }
  }
  
  function handleKeyPress(e) {
    if (e.key === "Enter") {
      submitGuess()
      return
    }
  
    if (e.key === "Backspace" || e.key === "Delete") {
      deleteKey()
      return
    }
  
    if (e.key.match(/^[aeiouhklmnpwʻ]$/)) {
      pressKey(e.key)
      return
    }

    if (e.key.match(/^[']$/)) {
        pressKey('ʻ')
        return
      }

  }
  
  function pressKey(key) {
    const activeTiles = getActiveTiles()
    if (activeTiles.length >= WORD_LENGTH) return
    const nextTile = guessGrid.querySelector(":not([data-letter])")
    nextTile.dataset.letter = key.toLowerCase()
    nextTile.textContent = key
    nextTile.dataset.state = "active"
  }
  
  function deleteKey() {
    const activeTiles = getActiveTiles()
    const lastTile = activeTiles[activeTiles.length - 1]
    if (lastTile == null) return
    lastTile.textContent = ""
    delete lastTile.dataset.state
    delete lastTile.dataset.letter
  }
  
  function submitGuess() {
    const activeTiles = [...getActiveTiles()]
    if (activeTiles.length !== WORD_LENGTH) {
      showAlert("Not enough letters")
      shakeTiles(activeTiles)
      return
    }
  
    const guess = activeTiles.reduce((word, tile) => {
      return word + tile.dataset.letter
    }, "")
  
    if (!dictionary.includes(guess)) {
      showAlert("Not in word list")
      shakeTiles(activeTiles)
      return
    }

    const targetWordArray = targetWord.split('')

    // First pass: Identify correct letters
    for(let i = 0; i < WORD_LENGTH; i++) {
      if (guess[i] === targetWordArray[i]) {
        activeTiles[i].dataset.mark = "correct";
        targetWordArray[i] = null;
      }
    }
  
    // Second pass: Identify letters in the wrong location
    for(let i = 0; i < WORD_LENGTH; i++) {
      if (activeTiles[i].dataset.mark !== "correct" && targetWordArray.includes(guess[i])) {
        activeTiles[i].dataset.mark = "wrong-location";
        targetWordArray[targetWordArray.indexOf(guess[i])] = null;
      }
    }

    // Third pass: Mark remaining letters as wrong
    for(let i = 0; i < WORD_LENGTH; i++) {
      if (!activeTiles[i].dataset.mark) {
        activeTiles[i].dataset.mark = "wrong";
      }
    }
  
    stopInteraction()
    activeTiles.forEach((...params) => flipTile(...params, guess))
  }
  
  function flipTile(tile, index, array, guess) {
    const letter = tile.dataset.letter
    const key = keyboard.querySelector(`[data-key="${letter}"i]`)
    setTimeout(() => {
      tile.classList.add("flip")
    }, (index * FLIP_ANIMATION_DURATION) / 2)
  
    tile.addEventListener(
      "transitionend",
      () => {
        tile.classList.remove("flip")
        // Use the mark set in submitGuess function
        tile.dataset.state = tile.dataset.mark;

        key.classList.add(tile.dataset.mark);
  
        if (index === array.length - 1) {
          tile.addEventListener(
            "transitionend",
            () => {
              startInteraction()
              checkWinLose(guess, array)
            },
            { once: true }
          )
        }
      },
      { once: true }
    )
  }  
  
  function getActiveTiles() {
    return guessGrid.querySelectorAll('[data-state="active"]')
  }

  function showAlert(message, duration = 1000, url = null) {
    const alert = document.createElement("div");
    if (url) {
        const link = document.createElement("a");
        link.href = url;
        link.target = "_blank";  // open in a new tab
        link.textContent = message;
        alert.appendChild(link);
    } else {
        alert.textContent = message;
    }
    alert.classList.add("alert");
    alertContainer.prepend(alert);
    if (duration == null) return;

    setTimeout(() => {
      alert.classList.add("hide");
      alert.addEventListener("transitionend", () => {
        alert.remove();
      });
    }, duration);
}
  
  function shakeTiles(tiles) {
    tiles.forEach(tile => {
      tile.classList.add("shake")
      tile.addEventListener(
        "animationend",
        () => {
          tile.classList.remove("shake")
        },
        { once: true }
      )
    })
  }
  

  function checkWinLose(guess, tiles) {
    if (guess === targetWord) {
        setTimeout(() => {
            showAlert("Click here to learn what " + targetWord.toUpperCase() + " means.",null,"http://wehewehe.org/gsdl2.85/cgi-bin/hdict?a=q&q=" + targetWord + "&fqv=textpukuielbert&af=1&fqf=ED")
            showAlert("You Win!",null)
          }, 1800);

      danceTiles(tiles)
      stopInteraction()
      return
    }
  
    const remainingTiles = guessGrid.querySelectorAll(":not([data-letter])")
    if (remainingTiles.length === 0) {
      showAlert("Click here to learn what " + targetWord.toUpperCase() + " means.",null,"http://wehewehe.org/gsdl2.85/cgi-bin/hdict?a=q&q=" + targetWord + "&fqv=textpukuielbert&af=1&fqf=ED")
      showAlert(targetWord.toUpperCase(), null)
      stopInteraction()
    }
  }
  
  function danceTiles(tiles) {
    tiles.forEach((tile, index) => {
      setTimeout(() => {
        tile.classList.add("dance")
        tile.addEventListener(
          "animationend",
          () => {
            tile.classList.remove("dance")
          },
          { once: true }
        )
      }, (index * DANCE_ANIMATION_DURATION) / 5)
    })
  }

let count = 0;
let countDown;
let timerDisplay = document.getElementById('timer');

document.getElementById('start').addEventListener('click', () => {
    clearInterval(countDown);  // To prevent multiple intervals on clicking start multiple times
    countDown = setInterval(() => {
        count++;
        let minutes = Math.floor(count / 60);
        let seconds = count % 60;
        minutes = minutes < 10 ? '0' + minutes : minutes;
        seconds = seconds < 10 ? '0' + seconds : seconds;
        timerDisplay.textContent = minutes + ':' + seconds;
    }, 1000);
});

document.getElementById('stop').addEventListener('click', () => {
    clearInterval(countDown);
});

document.getElementById('reset').addEventListener('click', resetTimer);

// Call this function to reset the timer at the end of each game
function resetTimer() {
    clearInterval(countDown);
    count = 0;
    timerDisplay.textContent = '00:00';
}
      